### ISSUE TITLE
Failure to load pymol plugin

### ISSUE THREAD

**Issue by rvhonorato** [LBC-LNBio/parKVFinder#2]
After a fresh install following the instructions in the repository, the pymol plugin fails to load. Instalation went ok with no errors.

On Pymol after loading `input/1fmo.pse` and trying to load the plugin, this error is shown in the console:
```
2020-10-12 16:46:05.478 python[60522:1302668] -[QNSApplication macMinorVersion]: unrecognized selector sent to instance 0x7f9935e44080
```
Trying to load it again results in:

```python
Traceback (most recent call last):
  File "/Users/rodrigo/software/anaconda3/lib/python3.7/site-packages/pmg_tk/startup/PyMOL_parKVFinder_tools.py", line 62, in <lambda>
    command=lambda s=self: PyMOL_parKVFinder_Tools(s))
  File "/Users/rodrigo/software/anaconda3/lib/python3.7/site-packages/pmg_tk/startup/PyMOL_parKVFinder_tools.py", line 70, in __init__
    self.parent = app.root
  File "/Users/rodrigo/software/anaconda3/lib/python3.7/site-packages/pmg_qt/mimic_pmg_tk.py", line 150, in root
    tkinter_init()
  File "/Users/rodrigo/software/anaconda3/lib/python3.7/site-packages/pmg_qt/mimic_pmg_tk.py", line 15, in tkinter_init
    raise RuntimeError('tkinter init failed')
RuntimeError: tkinter init failed
```
***
Full log
```
$ pymol
Cannot find license file.
 The license files (or license server system network addresses) attempted are
listed below.  Use LM_LICENSE_FILE to use a different license file,
 or contact your software provider for a license file.
Feature:       PYMOL_MAIN
Filename:      /Library/Application Support/Schrodinger/licenses
License path:  /Library/Application Support/Schrodinger/licenses:
FlexNet Licensing error:-1,359.  System Error: 2 "No such file or directory"
 PyMOL(TM) 2.4.0 - Incentive Product
 Copyright (C) Schrodinger, LLC

 This Executable Build integrates and extends Open-Source PyMOL.
 Detected OpenGL version 2.1. Shaders available.
 Detected GLSL version 1.20.
 OpenGL graphics engine:
  GL_VENDOR:   Intel Inc.
  GL_RENDERER: Intel(R) HD Graphics 6000
  GL_VERSION:  2.1 INTEL-14.6.18
No License File - For Evaluation Only (0 days remaining)
 Detected 4 CPU cores.  Enabled multithreaded rendering.
 Executive: Loading version 2.001000 session...
 Session was saved with: viewport 640, 455
2020-10-12 16:46:05.478 python[60522:1302668] -[QNSApplication macMinorVersion]: unrecognized selector sent to instance 0x7f9935e44080
Traceback (most recent call last):
  File "/Users/rodrigo/software/anaconda3/lib/python3.7/site-packages/pmg_tk/startup/PyMOL_parKVFinder_tools.py", line 62, in <lambda>
    command=lambda s=self: PyMOL_parKVFinder_Tools(s))
  File "/Users/rodrigo/software/anaconda3/lib/python3.7/site-packages/pmg_tk/startup/PyMOL_parKVFinder_tools.py", line 70, in __init__
    self.parent = app.root
  File "/Users/rodrigo/software/anaconda3/lib/python3.7/site-packages/pmg_qt/mimic_pmg_tk.py", line 150, in root
    tkinter_init()
  File "/Users/rodrigo/software/anaconda3/lib/python3.7/site-packages/pmg_qt/mimic_pmg_tk.py", line 15, in tkinter_init
    raise RuntimeError('tkinter init failed')
RuntimeError: tkinter init failed
```

**Comment by rvhonorato** [comment]
This issue is related to the PyMol installation in MacOS and not with KVFinder, https://github.com/schrodinger/pymol-open-source/issues/13.

My workaround to fix the issue was to install open-source PyMol using MacPort (macos 10.15.7):

```bash
$ sudo port install pymol py-pmw py-toml py-future
```
